### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by Vergenter** [huradoze/Statki1#1]
You are using global variables in https://github.com/huradoze/Statki1/blob/2fa6309044f130f4aaa51b2205f76befc4147579/Enemy.cpp#L9 and https://github.com/huradoze/Statki1/blob/2fa6309044f130f4aaa51b2205f76befc4147579/Bullet.cpp#L9
### First solution:

The quickest fix is to add a `Game` field in `Player`, `Bullet`, and `Enemy` classes. (The `Player` needs a `Game` pointer/object to create `bullet`).

Here's an example of how to add a `Game` pointer to a child class. Foo represents the `Game`, and Bar represents `Player`.

```cpp
class Foo;  // Forward declaration of Foo

class Bar {
private:
  Foo* fooPtr;  // Pointer to Foo

public:
  Bar(Foo* foo) : fooPtr(foo) {}
  // Other members of the Bar class
};

class Foo {
private:
  Bar bar;  // Instance of Bar

public:
  Foo() : bar(this) {}
  // Other members of the Foo class
};
```
### Second solution:

Another solution is to use the Singleton design pattern for the `Game` class. You can refer to the following link for more details: [Singleton Design Pattern](https://gameprogrammingpatterns.com/singleton.html).
### Third solution:

Similar to the first solution, the `Enemy` class would have a `Game` pointer/reference. Instead of directly updating the score in the https://github.com/huradoze/Statki1/blob/2fa6309044f130f4aaa51b2205f76befc4147579/Bullet.cpp#L32 the `Bullet` would call a method `onHit()` on the `Enemy` object, which would then update the score as it has pointer/reference to the `Game` object.
### Reason for your problem:

The `Game` and `GameState` are tightly coupled, there are multiple responsibilities assigned to one function/class, and other design issues. These can lead to difficulties in maintaining and understanding the code.

**Comment by huradoze** [comment]
@Vergenter  I am very happy that you have addressed my project and are helping me to solve my problem. I have chosen first solution. The game works almost as I would expect it to, however, when shooting down an enemy with a bullet, the game ends unexpectedly. Other aspects - collision with enemies or obstacles works flawlessly. Could you give me a hint as to where the error is? I suspect that the deletion mechanism is not working properly.

`#include "bullet.h"
#include "qgraphicsscene.h"
#include <QTimer>
#include <QList>
#include "enemy.h"
#include <QDebug>
#include "Game.h"

Bullet::Bullet(Game* game, QGraphicsItem *parent) : QObject(), QGraphicsPixmapItem(parent), game(game)
{
    // draw graphics
    setPixmap(QPixmap(":/images/bullet.png"));

    // make/connect a timer to move() the bullet every so often
    QTimer* timer = new QTimer(this);
    connect(timer, SIGNAL(timeout()), this, SLOT(move()));

    // start the timer
    timer->start(50);
}

void Bullet::move()
{
    // get a list of all the items currently colliding with this bullet
    QList<QGraphicsItem*> colliding_items = collidingItems();

    // if one of the colliding items is an Enemy, destroy both the bullet and the enemy
    for (int i = 0, n = colliding_items.size(); i < n; ++i)
    {
        if (typeid(*(colliding_items[i])) == typeid(Enemy))
        {
            // increase the score
            game->score->increase();

            // remove them from the scene (still on the heap)
            scene()->removeItem(colliding_items[i]);
            scene()->removeItem(this);

            // delete them from the heap to save memory
            delete colliding_items[i];
            delete this;

            // return (all code below refers to a non-existing bullet)
            return;
        }
    }

    // if there was no collision with an Enemy, move the bullet forward
    setPos(x(), y() - 10);
    // if the bullet is off the screen, destroy it
    if (pos().y() < 0)
    {
        scene()->removeItem(this);
        delete this;
    }
}`

`#ifndef BULLET_H
#define BULLET_H

#include <QGraphicsPixmapItem>
#include <QObject>

// Forward declaration of Game class
class Game;

class Bullet: public QObject, public QGraphicsPixmapItem {
    Q_OBJECT
public:
    Bullet(Game* game, QGraphicsItem *parent = nullptr);

public slots:
    void move();

private:
    Game* game; // Pointer to Game
};

#endif // BULLET_H`

`#ifndef ENEMY_H
#define ENEMY_H

#include <QGraphicsPixmapItem>
#include <QObject>

// Forward declaration of Game class
class Game;

class Enemy : public QObject, public QGraphicsPixmapItem {
    Q_OBJECT
public:
    Enemy(Game* game);

public slots:
    void move_to();
    void collision();

private:
    Game* game; // Pointer to Game
};

#endif // ENEMY_H`

`#include "enemy.h"
#include <QTimer>
#include <QGraphicsScene>
#include <QList>
#include <stdlib.h>
#include "game.h"

Enemy::Enemy(Game* game) : game(game)
{
    QTimer* timer = new QTimer();
    int ranx, rany, ran;
    ranx = rand() % 200 + 200;
    rany = rand() % 200 + 200;
    ran = rand() % 4;
    setPixmap(QPixmap(":/images/enemy.png"));
    setTransformOriginPoint(50, 50);
    setRotation(180);
    if (ran == 0)
    {
        setPos(game->player->pos().x() + ranx, game->player->pos().y() + rany);
    }
    if (ran == 1)
    {
        setPos(game->player->pos().x() - ranx, game->player->pos().y() + rany);
    }
    if (ran == 2)
    {
        setPos(game->player->pos().x() + ranx, game->player->pos().y() - rany);
    }
    if (ran == 3)
    {
        setPos(game->player->pos().x() - ranx, game->player->pos().y() - rany);
    }

    connect(timer, &QTimer::timeout, [&, this]() {
        move_to();
    });

    timer->start(50);
}

void Enemy::collision()
{
    QList<QGraphicsItem*> colliding_items = collidingItems();
    for (int i = 0, n = colliding_items.size(); i < n; i++)
    {
        if (typeid(*(colliding_items[i])) == typeid(Player))
        {
            game->health->decrease();
            game->ifGameOver();
            scene()->removeItem(this);
        }
    }
}

void Enemy::move_to()
{
    if (game->player->pos().x() > pos().x())
        setPos(pos().x() + 2, pos().y());
    else if (game->player->pos().x() < pos().x())
        setPos(pos().x() - 2, pos().y());
    if (game->player->pos().y() > pos().y())
        setPos(pos().x(), pos().y() + 2);
    else if (game->player->pos().y() < pos().y())
        setPos(pos().x(), pos().y() - 2);
    collision();
}`

`#ifndef GAME_H
#define GAME_H

#include <QGraphicsView>
#include <QWidget>
#include <QGraphicsScene>
#include <QTimer>
#include "Player.h"
#include "Score.h"
#include "Health.h"
#include "enemy.h"

// Forward declaration of Player class
class Player;

class Game: public QGraphicsView
{
public:
    Game(QWidget *parent = nullptr);

    QGraphicsScene *scene;
    Player *player;
    Score *score;
    Health *health;
    QTimer *endofgame;

    void ifGameOver();

private:
    QTimer *timer;
    QTimer *timer1;
    QTimer *timer2;
};

#endif // GAME_H`

`#include "Game.h"
#include <QTimer>
#include <QGraphicsTextItem>
#include <QFont>
#include "Enemy.h"
#include <QBrush>
#include <QImage>
#include "qgraphicsscene.h"
#include <motionless.h>
#include "score.h"
#include <QGraphicsScene>
#include <QApplication>
#include "Player.h"

Game::Game(QWidget *parent) {
    // create the scene
    scene = new QGraphicsScene();
    scene->setSceneRect(0, 0, 900, 900);
    setBackgroundBrush(QBrush(QImage(":/images/nakladka.png")));

    // make the newly created scene the scene to visualize
    setScene(scene);
    setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
    setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
    setFixedSize(900, 900);

    // create the player
    player = new Player(this);
    player->setPos(300, 300);
    player->setFlag(QGraphicsItem::ItemIsFocusable);
    player->setFocus();
    scene->addItem(player);

    // create the score/health
    score = new Score();
    scene->addItem(score);
    health = new Health();
    health->setPos(health->x(), health->y() + 25);
    scene->addItem(health);

    // spawn enemies
    timer = new QTimer();
    QObject::connect(timer, SIGNAL(timeout()), player, SLOT(create()));
    timer->start(5000);

    // spawn obstacles
    timer1 = new QTimer();
    QObject::connect(timer1, SIGNAL(timeout()), player, SLOT(create_obstacle_ice_hill()));
    timer1->start(5000);

    timer2 = new QTimer();
    QObject::connect(timer2, SIGNAL(timeout()), player, SLOT(create_obstacle_fale()));
    timer2->start(3000);

    show();
}

void Game::ifGameOver()
{
    if (health->getHealth() <= 3)
    {
        scene = new QGraphicsScene();
        scene->setSceneRect(0, 0, 900, 900);
        setScene(scene);
        setBackgroundBrush(QBrush(QImage(":/images/game_over.png")));
        timer->stop();
        timer1->stop();
        timer2->stop();

        // Dodaj tekst z wynikiem
        QGraphicsTextItem* scoreText = new QGraphicsTextItem();
        scoreText->setPlainText("Wynik: " + QString::number(score->getScore()));
        QFont scoreFont("Helvetica", 24);
        scoreText->setFont(scoreFont);
        int xPos = scene->width() / 2 - scoreText->boundingRect().width() / 2;
        int yPos = 100;
        scoreText->setPos(xPos, yPos);
        scene->addItem(scoreText);

        QTimer::singleShot(7000, QApplication::instance(), &QApplication::quit);
    }
}`

**Comment by Vergenter** [comment]
The code in the post is not in the best form for me to analyse it. It would be helpful if you could commit the code first, even to a different branch.

One thing to note is that you are deleting this in the middle of a method and planning to execute code later, which results in undefined behaviour. Deleting this removes the currently executing object. You can refer to the following link for more information: [delete this in C++](https://www.geeksforgeeks.org/delete-this-in-cpp/).

**Comment by huradoze** [comment]
@Vergenter I just added a new repository - https://github.com/huradoze/Statki---kasowanie . When I added the line of code in obstacle_ice_hill that was responsible for deleting the bullet and obstacle from the scene, the game worked fine. This is probably not related, but I wanted to mention it.

**Comment by huradoze** [comment]
I modified the void Bullet::move() function a little, removing two lines:
scene()->removeItem();
delete colliding_items[i];
the game works correctly and does not shut down. I don't know if this is a good solution, whereas everything seems to work correctly.
`void Bullet::move()
{
    // get a list of all the items currently colliding with this bullet
    QList<QGraphicsItem*> colliding_items = collidingItems();

    // if one of the colliding items is an Enemy, destroy both the bullet and the enemy
    for (int i = 0, n = colliding_items.size(); i < n; ++i)
    {
        if (typeid(*(colliding_items[i])) == typeid(Enemy))
        {
            // increase the score
            game->score->increase();

            // remove them from the scene (still on the heap)
            scene()->removeItem(colliding_items[i]);
            //scene()->removeItem(this);

            // delete them from the heap to save memory
            //delete colliding_items[i];
           delete this;

            // return (all code below refers to a non-existing bullet)
            return;
        }
    }

    // if there was no collision with an Enemy, move the bullet forward
    setPos(x(), y() - 10);
    // if the bullet is off the screen, destroy it
    if (pos().y() < 0)
    {
        scene()->removeItem(this);
        delete this;
    }
}`

**Comment by Vergenter** [comment]
### You are leaking memory

The `delete` calls were necessary, but they are in the wrong place.
### `delete this` is a mistake

As previously mentioned, it should never be done.
### Solution for `new` and `delete`

Instead, consider using a shared pointer, as it is a more advanced approach, but it will simplify your code. You can learn more about shared pointers here: [Smart Pointers in C++](https://www.geeksforgeeks.org/smart-pointers-cpp/)

### Use git as it is system for versioning your code.
1. Install git on your system using https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
2. Set your git username: `git config --global user.name "FIRST_NAME LAST_NAME"`
3. Set your email address: `git config --global user.email "MY_NAME@example.com"`
4. save your repository to disk `git clone https://github.com/huradoze/Statki1.git`

### send changes to github:
1. modify your code
2. add changes that you made using `git add "FILE_NAME"` to add all files `git add *`
3. save your added changes, using `git commit`
4. save you changes on github using `git push`
